NAME=expander

META=http://downloads.lappsgrid.org/deiis/metamap.tgz
PY=http://downloads.lappsgrid.org/deiis/pymetamap.tgz

include ../Makefile.master

download:
	if [ ! -x $(META) ] ; then wget $(META) ; fi
	if [ ! -x $(PY) ] ; then wget $(PY) ; fi

